server:
  servlet:
    context-path: /zs
spring:
  datasource:
    username: root
    password: woshiroot123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zj_blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
      # 文件临时保存的目录
      location: /tmp/fileStore
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

file:
  upload:
    realDir: /static/fileStore
  # 访问静态资源的域名
  static:
    domain:  http://localhost:8080/zs
openapi:
  nvidia:
    secretKey: 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


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: zsUserToken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

zs:
  boot:
    aes:
      key: zs-boot
    sso:
      paths: /api/admin/**,/api/manager/**

# mybatis配置信息
mybatis-plus:
  # 打印SQL语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 全局配置
  global-config:
    db_config:
      # 全局逻辑删除的字段名
      logic-delete-field: deleted
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
docusaurus:
  dir:
    path: /root/zjBlog/zj-docusaurus-blogs
  nginx:
    site:
      dir:
        path: /root/zjBlog/zj-docusaurus-blogs/build
      history:
        dir:
          path: /root/zjBlog/zj-docusaurus-blogs/history
